import { Suspense } from "react";
import StoreProvider from "./StoreProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./styles/globals.css";
import "./styles/text-editor.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Editor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Suspense>{children}</Suspense>
        </StoreProvider>
      </body>
    </html>
  );
}
